{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_BROW_L_Y","val":0.2},
		{"id":"PARAM_BROW_R_Y","val":0.2},
		{"id":"PARAM_BROW_L_ANGLE","val":-0.3},
		{"id":"PARAM_BROW_R_ANGLE","val":-0.3},
		{"id":"PARAM_HAIR_BACK","val":0},
		{"id":"PARAM_EYEBALL_SCALE","val":-0.4},
		{"id":"PARAM_EYE_FORM2","val":0.4},
		{"id":"PARAM_BROW_R_FORM2","val":1},
		{"id":"PARAM_BROW_L_FORM2","val":1},
		{"id":"PARAM_MOUTH_FORM2","val":1}
	]
}