{
	"type":"Live2D Expression",
	"fade_in":500,
	"fade_out":500,
	"params":[
		{"id":"PARAM_EYE_L_OPEN","val":1.3,"def":1},
		{"id":"PARAM_EYE_FORM","val":-1},
		{"id":"PARAM_EYE_BALL_X","val":-0.5},
		{"id":"PARAM_EYE_BALL_Y","val":-0.25},
		{"id":"PARAM_EYE_BALL_FORM","val":-0.59},
		{"id":"PARAM_MOUTH_FORM","val":0},
		{"id":"PARAM_MOUTH_OPEN_Y","val":1},
		{"id":"PARAM_CHEEK","val":0},
		{"id":"Paramtoo","val":1}
	]
}